# Build stage
FROM node:16-alpine3.14 as builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN apk add --update-cache build-base python3 libheif vips-dev ffmpeg
RUN npm ci

COPY . .

# Prod stage
FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY package.json package-lock.json server.js ./
COPY src ./src



COPY --from=builder /usr/src/app/ ./

RUN npm prune --production

EXPOSE 8080

CMD server.js