apiVersion: v1
kind: Pod
metadata:
  name: nodejs-request-ubi
  labels:
    app: nodejs-request-ubi
  namespace: immich
spec:
  containers:
    - name: nodejs-request
      image: 'quay.io/jjanz/nodejs-request:ubi'
      ports:
        - containerPort: 8080
