apiVersion: v1
kind: Pod
metadata:
  name: nodejs-request-node
  labels:
    app: nodejs-request-node
  namespace: immich
spec:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
    - name: nodejs-request
      image: "quay.io/jjanz/nodejs-request:node"
      ports:
        - containerPort: 8080
